"""Initial migration

Revision ID: b67a2216d087
Revises: 
Create Date: 2026-03-23 20:17:14.830625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b67a2216d087'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='化合物名称'),
    sa.Column('cas_number', sa.String(length=50), nullable=True, comment='CAS号'),
    sa.Column('molecular_formula', sa.String(length=100), nullable=True, comment='分子式'),
    sa.Column('molecular_weight', sa.Float(), nullable=True, comment='分子量'),
    sa.Column('structure_smiles', sa.Text(), nullable=True, comment='SMILES结构'),
    sa.Column('purity', sa.Float(), nullable=True, comment='纯度(%)'),
    sa.Column('source', sa.String(length=100), nullable=True, comment='来源'),
    sa.Column('storage_condition', sa.String(length=100), nullable=True, comment='存储条件'),
    sa.Column('remarks', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cas_number')
    )
    op.create_table('experiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('compound_id', sa.Integer(), nullable=False),
    sa.Column('experiment_name', sa.String(length=200), nullable=False, comment='实验名称'),
    sa.Column('virus_type', sa.String(length=50), nullable=True, comment='病毒类型'),
    sa.Column('cell_line', sa.String(length=100), nullable=True, comment='细胞系'),
    sa.Column('experiment_date', sa.Date(), nullable=False, comment='实验日期'),
    sa.Column('operator', sa.String(length=50), nullable=True, comment='操作人员'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='实验状态'),
    sa.Column('protocol', sa.Text(), nullable=True, comment='实验方案'),
    sa.Column('remarks', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['compound_id'], ['compounds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experiment_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('concentration', sa.Float(), nullable=True, comment='药物浓度(μM)'),
    sa.Column('viability', sa.Float(), nullable=True, comment='细胞存活率(%)'),
    sa.Column('inhibition_rate', sa.Float(), nullable=True, comment='抑制率(%)'),
    sa.Column('ic50', sa.Float(), nullable=True, comment='IC50(μM)'),
    sa.Column('cc50', sa.Float(), nullable=True, comment='CC50(μM)'),
    sa.Column('si', sa.Float(), nullable=True, comment='选择性指数(SI)'),
    sa.Column('raw_data', sa.Text(), nullable=True, comment='原始数据JSON'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('experiment_results')
    op.drop_table('experiments')
    op.drop_table('compounds')
    # ### end Alembic commands ###
